select = ["E", "F", "B", "I", "N", "A", "COM", "C4", "EXE", "ISC", "G", "PIE", "PT",
		"RSE", "RET", "SIM", "TID", "ARG", "PD", "PL", "NPY", "RUF",
]

line-length = 100
fix = false
show-source = true
target-version = "py310"

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

namespace-packages = [
	"cats_fun_site",
	"polls",
]

[per-file-ignores]
# Ignore 'F401' (unused-import) in all '__init__.py' files.
"__init__.py" = ["F401"]

# Ignore 'RUF001' (contains ambiguous unicode character) in all 'forms.py' files and
# files in utils folders.
"forms.py" = ["RUF001"]
"**utils/**.py" = ["RUF001"]

# Ignore 'COM812' (trailing comma missing) and
# 'I001' (import block is un-sorted or un-formatted) in all django's migrations files
"**/migrations/**" = [
	"COM812",
	"I001",
]

# Ignore 'PT009' (use a regular `assert` instead of unittest-style `assertIs`)
"test*.py" = ["PT009"]

[pydocstyle]
convention = "google"

[pylint]
max-args = 7
